#!/bin/bash -l 

# Request time (maximum 720 hours for 1-processor jobs, 120 hours for MPI jobs)
#$ -l h_rt=12:00

#$ Request multiple cores (on the same machine)
#$ -pe omp 4

# Move input and output streams to a single file
#$ -j y

module load openmpi/4.1.5_gnu-12.2.0
module load quantumespresso/7.2

export PSEUDO_DIR=$ESPRESSO_PSEUDO
export BIN_DIR=$SCC_QUANTUMESPRESSO_BIN

# Run example
./run_example
